export default function Page() {
  return (
    <div>
      <h3>2023-2024</h3>
      <iframe
        allow="autoplay"
        height="480"
        src="https://drive.google.com/file/d/1-7GOVrgZszosh1jDyKSdGo_2ohLZGb62/preview"
        width="640"
      ></iframe>
      <iframe
        src="https://drive.google.com/file/d/1buiS4OrSIpZAywC8lPso2M3agEQ__GQg/preview"
        width="640"
        height="480"
        allow="autoplay"
      ></iframe>
      <h3>2022-2023</h3>
      <iframe
        src="https://drive.google.com/file/d/1Oa-d6v3UFWpvPrOX44DDQZj2X9hdfqgB/preview"
        width="640"
        height="480"
        allow="autoplay"
      ></iframe>
      <iframe
        src="https://drive.google.com/file/d/1ynqgnqjaWtaXIm_E9u4QBYutB9EF6Cuc/preview"
        width="640"
        height="480"
        allow="autoplay"
      ></iframe>
      <h3>2021-2022</h3>
      <iframe
        src="https://drive.google.com/file/d/1wn3_NKURByEFl4mjijxhI3caAGFw3yPv/preview"
        width="640"
        height="480"
        allow="autoplay"
      ></iframe>
      <iframe
        src="https://drive.google.com/file/d/1NazabDvm10puMkut7Yji2EEIMUnxSV3o/preview"
        width="640"
        height="480"
        allow="autoplay"
      ></iframe>
      <h3>2020-2021</h3>
      <iframe
        src="https://drive.google.com/file/d/19xZ5VIo21VedVI9Nbk0gB23PeetsfZuq/preview"
        width="640"
        height="480"
        allow="autoplay"
      ></iframe>
      <br />
      <iframe
        src="https://drive.google.com/file/d/1SfTLtiAm2-SnBFljmVRbCPmyXORBv2Rl/preview"
        width="640"
        height="480"
        allow="autoplay"
      ></iframe>
    </div>
  );
}
